version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: crmportal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "11099:8080"
    networks:
      - webnet
networks:
  webnet:      
